name: smartwatch_companion
description: Companion app for ESP32-C3 Smartwatch

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # BLE
  flutter_blue_plus: ^1.31.15

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Image processing
  image: ^4.1.7

  # File & storage
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # Permissions
  permission_handler: ^11.3.1

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2     # animasi mudah & ringan
  fl_chart: ^1.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
